### ISSUE TITLE
Revise intro

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#10]
I have revised intro but still the relationship between the beginning and when EAs are mentioned is not too good. 
The intro does not mention anything about our methodology or the title, and focuses on the subtitle. @pacastillo comments too that some things should be moved to the abstract. All in all, I think it needs some additions. I assign @ccottap but anyone can work on it.

**Comment by fcofdezdevega** [comment]
Anybody considering something must be said, or better explained.  Please, do it yourself.

**Comment by JJ** [comment]
That's what I have done. Check the commit above. But it still needs more revision.
