### ISSUE TITLE
20 times

### ISSUE THREAD

**Issue by fcofdezdevega** [frchavez/PPSN_Consumo_2016#12]
@ccottap :  In the results section we state:

we notice that raspberry pi and handheld devices are the least demanding ones,
requiring 20 times less energy to run the same algorithm when compared with
more standard computers:

This data was computed from the previous table that has been now supress, given that the info is in the graphs.  But I consider it quite difficult for readers to understand now were that 20 comes from.

So carlos, decide if this may remain, or instead rewriten differently.

**Comment by ccottap** [comment]
I would change it to "an order of magnitude less energy". Even with the table, 20 would not be very straightforward for the reader because one would have to average non-handheld devices and then deal with some variation due to population size.
