### ISSUE TITLE
Global revision

### ISSUE THREAD

**Issue by ccottap** [frchavez/PPSN_Consumo_2016#14]
The paper has all sections completed but needs still (a lot of) revision. I have done my best on methodology and results, but the rest (and even these two sections) requires polishing:

- Most importantly, check for continuity, whether intro and conclusions are in line with the abstract and the results.
- There is an issue about the blade that requires clarification in a footnote @frchavez
- Typos are scattered throughout the paper. Please proofread.
- References are a pain in the butt. Bibtems show up even if you do not use them, and even those in use are seldom in Springer format. Formatting can be forgiven but unused bibitems have to be removed. I guess this should be done by whomever typed them in the first place ( @frchavez ? @fcofdezdevega ?) 

The more eyes, the more we see so please @JJ @pacastillo @mjdiazster @frchavez @fcofdezdevega take a deep look at the paper.

**Comment by JJ** [comment]
OK, got it.

**Comment by fcofdezdevega** [comment]
I have fixed references problems and remove those that are not used.
