### ISSUE TITLE
Footnotes should not be used

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#15]
Even less so if they are URLs, even less so if they are *long* URLs that go beyond line limits. Either change them to citations using the proper format, or eliminate them completely. I would go for the second, they are really not needed.

**Comment by ccottap** [comment]
The software used has to be unambiguously identified (just the name is not enough, try googling "hardware monitor" for example). In same cases there may be a paper which can be referenced for this purpose but not always. The information can be forced into a citation if you prefer so.

**Comment by JJ** [comment]
You can also reference web pages. In fact, you should do it.
