### ISSUE TITLE
How come the approximation ration have an error bar?

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#16]
There's an horizontal error bar in Fig 2.b. If the fitness attained is exactly the same irrespective of the run, how com it have an error bar?

**Comment by ccottap** [comment]
Each run has a different result that depends on the seed, not on the machine. For that reason points and errorbars (corresponding to the dispersion for a given population size) are vertically aligned.

**Comment by JJ** [comment]
So the 30 runs have 30 different seeds, but these seeds are the same for
all machines?

**Comment by JJ** [comment]
OK, I see they do. Thanks!

**Comment by JJ** [comment]
But this would really not be needed, right? You could as well have used the same random seed for the 30 runs, eliminating one source of randomness.

**Comment by JJ** [comment]
And this takes me back to my previous suggestion, to use evaluations and not degre of termination, but even if you do use degree of termination, why use error bars and not the value itself? If you are interested if power consumption for a degree of termination, why average it over runs?
