### ISSUE TITLE
Change the title from "evolutionary algorithms" to "genetic programming"

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#17]
That is what the paper does, and it is quite clear at the beginning of the "Methodology" section. That, or else explain how to extend these results to other evolutionary algorithms (which I guess is kind of difficult)

**Comment by fcofdezdevega** [comment]
Initially we wanted to include both GA and GP, although finally for several reason we only included GP algorithm.  But it is a test case for our general idea, and I think we are trying to to tell exactly that.

If we use GP in the title, we will supress a large numbe of future readers, so I prefer to maintian EAs.

**Comment by ccottap** [comment]
I also find EA better than GP. I think we have not done anything strictly GP-based, like playing with parameters such as tree depth or alike, so I find the study EA-generic in that sense.

**Comment by JJ** [comment]
Actually, you haven't done anything specific to GP but doing the
experiments *only* with GP, so I see your point here.

**Comment by ccottap** [comment]
Comments on wide applicability to other EAs introduced.
