### ISSUE TITLE
Power consumption vs energy consumption

### ISSUE THREAD

**Issue by ccottap** [frchavez/PPSN_Consumo_2016#18]
I find this a technicality but an important one, at least formally. I think we are always referring to energy consumption and have used some times _power_ as a loose synonym (which in this technical context is not appropriate). So probably all instances of "power consumption" should be changed to either "energy consumption" or to "power delivered" depending on what is meant in each specific case. I am tagging here the guys from the Computer Architecture area who are more versed in this issue.
@JJ @pacastillo @frchavez

**Comment by JJ** [comment]
OK, I'll check it out. But do you want it changed for the final version of
this paper, or for later?

**Comment by ccottap** [comment]
I think we'd better fix this for the final version, before everything gets carved in stone. 

There are 11 instances of "power consumption" and I think that in most cases changing it to either "energy consumption" or "power delivered" would make sense (but doubly checking this would be better).

**Comment by JJ** [comment]
OK

2016-06-01 9:28 GMT+02:00 Carlos Cotta <notifications@github.com>:

> I think we'd better fix this for the final version, before everything gets
> carved in stone.
>
> There are 11 instances of "power consumption" and I think that in most
> cases changing it to either "energy consumption" or "power delivered" would
> make sense (but doubly checking this would be better).
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/frchavez/PPSN_Consumo_2016/issues/18#issuecomment-222914629>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAB9PjO4t2MSy5VRrYEt4sj_0usALoPks5qHTS6gaJpZM4IqSoT>
> .
>



-- 
JJ

**Comment by ccottap** [comment]
Reopened because occurences of ambiguous phrase "power consumption" still present in the paper.
