### ISSUE TITLE
Can we please switch to using .bib? 

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#2]
It's much more convenient. Do you have the .bib file for those already included?

**Comment by JJ** [comment]
While you're at it, please, PLEASE, fix the references. Most of them are wrong. 14 does not say how published and no year, 13 does not say how it was publsihed, 7 no editors, 6 is what? proceedings?, 4 no editor, 3 should say URL, 2 don't see what is it about, and 1 neither...

**Comment by ccottap** [comment]
I concur. Please, let's use .bib.

**Comment by ccottap** [comment]
Someone please upload the .bib file? @fcofdezdevega @frchavez

**Comment by ccottap** [comment]
This issue has turned from a matter of convenience to a major hindrance. There's a lot of cleansing to be done here and editing bibitems would be pointless. **Please, someone include the .bib files**.

**Comment by fcofdezdevega** [comment]
I think we don't have enough time to fix this.  Better to leave as it is here, and probably reviewers will ask us to improve (what will be easy).

**Comment by ccottap** [comment]
If bibitems are going to be used someone will have to check them one by one and see if they are actually referenced in the paper. Now there are many of them which are no longer being cited (but still appear in the references) @frchavez @fcofdezdevega

**Comment by fcofdezdevega** [comment]
Already checked, fixed and removed those that are not used.
