### ISSUE TITLE
Can we comment on the title?

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#3]
It's not a survey, it's not a group of new energy aware algorithms. We are taking measurements of particular algorithms in several devices. The title should reflect that.
Please @ccottap and @pacastillo also comment on that.

**Comment by ccottap** [comment]
Just proposed a new title in line with the actual contents of the paper and tweaked the previous title as a subtitle (which can be removed altogether)

**Comment by JJ** [comment]
I like it more except for the "in" evolutionary algorithms. If @frchavez think it's OK, close the issue (via a commit)

**Comment by ccottap** [comment]
Pending: If @frchavez think it's OK, close the issue

**Comment by fcofdezdevega** [comment]
Well, basically we should change EAs for GP, given that it is the algorithm tested.  Yet, I prefer EAs in the title given that it is more general, and will probably atract more readers.  I will simply see if some sentence needs to be added to make it clear that this is the first attempt to meassure that for Eas, although we have particularized for GP.

I'll thus close thie issue.
