### ISSUE TITLE
Include results graph

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#6]
To make things a bit clearer, I think we need a graph. Are results in some .csv format somewhere? Or can someone upload them here?

**Comment by ccottap** [comment]
I did generate errorbars of time, power, etc. It would be convenient to generate such graphs with curves for each system. But we need standard errors for this. If we attempt to compare means without this information we will be thouroughly (and rightfully) thrashed.

**Comment by JJ** [comment]
We need to compare means or expected value only if there is such a thing,
which will depend on the distribution. I would rather compare median, which
always exists.

2016-04-12 14:17 GMT+02:00 Carlos Cotta <notifications@github.com>:

> I did generate errorbars of time, power, etc. It would be convenient to
> generate such graphs with curves for each system. But we need standard
> errors for this. If we attempt to compare means without this information we
> will be thouroughly (and rightfully) thrashed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/frchavez/PPSN_Consumo_2016/issues/6#issuecomment-208875232>
>



-- 
JJ

**Comment by ccottap** [comment]
The mean exists but if the question is whether it is an appropriate estimator, the answer ought to be 'yes': dissipated power is an average of instantaneous power over a time interval, and hence according to the CLT it should be normally distributed. In any case, the issue would be the same if the median was used: it is uninformative to compare distributions unless interquartile distance or other disperson measure is provided.

**Comment by JJ** [comment]
I mean average over 30 measures. If it's not centrally distributed, the
average is not informative.

If you mention the median, how should you report the measure? It's for a
friend :-)

**Comment by ccottap** [comment]
Maybe with confidence intervals (95% or alike). There may be specific functions in statistical packages for this (surely R has something to this avail). Providing the interquartile distance (range from p25 to p75) would also do because this information can be used to compute such intervals, I think.

**Comment by ccottap** [comment]
I'm closing this issue. We have many figures now.

**Comment by JJ** [comment]
You should use line, and not bar, graphs for the representation. Can't really compare the change from one population size to the next, and besides bars should be used only for categories. Fig 1 a) and b) should be labeled also in the figure itself.

**Comment by JJ** [comment]
Fig 2 should also include the symbols for every device. And Raspberry Pi and Blade use the same pattern. Besides, you are not using a log y in this graph, you should try and use the same scale for all energy graphs.

**Comment by JJ** [comment]
Still think that Fig 1 should use lines, not bars... And that the dashed lines for Raspberry pi and Blade are still the same, can't make them out...

**Comment by ccottap** [comment]
The figure would be very cluttered with overlapping lines and errorbars, hence the use of a barchart. Re fig 2b, I was running out of line styles- Hopefully data symbols can help to distinguish between them.

**Comment by JJ** [comment]
I am sure Tufte would be perfectly OK with that explanation, so who am I to
say it's wrong?
