### ISSUE TITLE
Results in SI units

### ISSUE THREAD

**Issue by ccottap** [frchavez/PPSN_Consumo_2016#7]
I'd avise to report results using SI units. Thus, I think we should use Joules instead of KWh. In addition to adhering to scientific standards, we would get rid of large negative exponents. cc: @mjdiazster @frchavez @pacastillo

**Comment by ccottap** [comment]
We have to report also the standard errors of the mean for power, time, and energy.

**Comment by mjdiazster** [comment]
I have added a column with Joules and I am changing the table with devices characteristics in the methodology file.

**Comment by JJ** [comment]
Agh, the results section is in Spanish. Never, ever, do this. Ever. Write
in good or bad English but do it in English.

**Comment by ccottap** [comment]
Great. I'm in favor or removing the KWh column and leave just J. 

Another issue: I just realized the time and energy reported are cummulative values for the 30 runs. I suggest reporting mean values (hence my previous remark on standard errors). I think that would be more informative because it would show the dispersion of the data, and easier for the reader that would not have to take to 30x factor into account.

Is the tablet energy correctly reported? There's on order of magnitude difference between values for 200 and 400.

**Comment by pacastillo** [comment]
The energy consumption in individual runs (in the Android Tablet) are as follows:

![captura de pantalla 2016-04-12 a la s 15 00 22](https://cloud.githubusercontent.com/assets/2456/14460720/51f5a8cc-00bf-11e6-9d65-1fc5757c98a4.png)

**Comment by ccottap** [comment]
Fine @pacastillo, I was afraid an average value had slipped in with the cummulative values. Anyway, I'm strongly in favor of turning everything into means +- std.err.

**Comment by JJ** [comment]
Please use English notation for quantities, not Spanish notation.

**Comment by fcofdezdevega** [comment]
Como ya he dicho por otro lado, hay que escribir la sección de resultados completa.  Comienzo a meter texto, pero todos podéis colaborar, y en cuánto podáis meter las gráficas que vayamos teniendo, porque aunque no sean las definitivas, servirá para ver lo que nos cabe en 10 páginas.

**Comment by fcofdezdevega** [comment]
En cuanto a medir en Julios, por mi no hay problema.

**Comment by fcofdezdevega** [comment]
Digo yo que en la tabla de resultados, o ponemos Julios o Kw/h, pero no ambas, por que son dos unidades diferente para la misma cosa.

¿Todos de acuerdo en dejar Julios y eliminar Kw/h?  Pues si es así, ánimo Carlos, tú que hiciste la propuesta, rectifica la tabla :-)

**Comment by fcofdezdevega** [comment]
La Tabla 3 entiendo que se refiere a GP no a GA.  Si es así faltarían los datos de Terminales y Funciones, pero si son los estándar podemos indicar los del libro de Koza y listo.

**Comment by fcofdezdevega** [comment]
Si esto es así, falta la tabla del GA ¿no?  Lo suyo es colocar dos columnas en esa tabla, una para GA y otra para GP.

@mjdiazster encárgate de fundir las dos tablas que hay ahora mismo en una, y encárgate de revisar si las probabilidades de cruce y mutación para lilgp están bien, porque ahora mismo tienen los mismos valores que los del GA, y creo que ha sido por corta/pega.

**Comment by fcofdezdevega** [comment]
@frchavez ¿Cómo es que el blade consume menos con 1000 individuos que con 500?  Consumo instantaneo me refiero.

**Comment by fcofdezdevega** [comment]
@mjdiazster @frchavez @pacastillo Oye, confirmado todos que el consumo que estamos poniendo en la tabla es sólo el del proceso, y no se incluye ahí el total del equipo ¿correcto?

**Comment by pacastillo** [comment]
Sí, eso es.
En el caso de Android sólo se toma el consumo del proceso, y no del sistema operativo completo (u otras aplicaciones)

**Comment by ccottap** [comment]
We can use the table to report mean times, and use some nice charts to depict energy and power. I think I have all the data, so I can produce these (tomorrow -- tonight I'm celebrating we advance to UCL semis :)).

**Comment by fcofdezdevega** [comment]
Acabo de añadir la tabla de datos del GA para poder también comentarlos si hay espacio en el paper, que parece que sí, dado que estamos en 8 páginas aún.  Creo que   @ccottap  quiere hoy hacer alguna estadística más.

**Comment by ccottap** [comment]
@fcofdezdevega De entrada el GA lo dejaría fuera, ya que no tenemos datos para todas las plataformas. Creo que vamos a estar justos de espacio además...

**Comment by pacastillo** [comment]
efectivamente... el GA no se ha ejecutado en el tablet Android    :/

**Comment by fcofdezdevega** [comment]
Si lo dejamos fuera hay que quitar todo lo de FPGA, porque ésta sólo se ha usado para el GA simple.  Por mi parte no hay problema en quitar todo esto, pero me temo que se quede corto si quitamos todo eso.

@ccottap @pacastillo  De momento le pongo comentarios a todo lo relativo a FPGAs y GA.  Si vemos que queda corto lo volvemos a activar.

 @frchavez confirma lo que preguntaba del blade para saber si está bien y cerramos este hilo.

**Comment by ccottap** [comment]
Queda pendiente esto: 
@frchavez  confirma lo que preguntaba del blade para saber si está bien y cerramos este hilo.

**Comment by fcofdezdevega** [comment]
Ya lo confirmó, parece que salió esto aunque es extraño.

Paco.

On Thu, Apr 14, 2016 at 10:08 PM, Carlos Cotta <notifications@github.com>
wrote:

> Queda pendiente esto:
> @frchavez <https://github.com/frchavez> confirma lo que preguntaba del
> blade para saber si está bien y cerramos este hilo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/frchavez/PPSN_Consumo_2016/issues/7#issuecomment-210127431>
>



-- 
fcofdez.wordpress.com
http://sites.google.com/site/fcofdezdevegaweb/

------------------New book --------------------
Parallel and Distributed Computational Intelligence
Series: Studies in Computational Intelligence , Vol. 269
Francisco Fernández de Vega; Erick Cantú-Paz, (Eds.)
2010, VI, 354 p., Hardcover
ISBN: 978-3-642-10674-3
http://www.springer.com/engineering/book/978-3-642-10674-3?detailsPage=toc
-----------------------------------------------


Dr. Francisco Fernández de Vega.
Titular de Universidad.
Departamento de Tecnología de los Computadores y de las Comunicaciones.
http://fcofdez.wordpress.com/
http://www.unex.es/unex/grupos/grupos/gea
Universidad de Extremadura.
Tf:    924 38 70 68
Fax: 924 30 37 82
Centro Universitario de Mérida.
C/Sta. Teresa de Jornet, 38.
06800 Mérida - Badajoz.
SPAIN.

e-mail: fcofdez@unex.es
           fcofdezdevega@gmail.com

**Comment by ccottap** [comment]
Sí, lo de la anomalía más o menos lo explicó. Lo que faltaría por confirmar es que los datos de potencia/energía son netos (descontando el consumo base).

**Comment by fcofdezdevega** [comment]
Ya están los datos actualizados en las tablas, así que puedes rehacer los gráficos.
