### ISSUE TITLE
Device Table

### ISSUE THREAD

**Issue by ccottap** [frchavez/PPSN_Consumo_2016#8]
I think we should add a column with information on the OS running in each device. 
Some entries have missing information (cores&memory for Xilinx and smartphone, processor details for smartphone) that needs being completed. 
cc: @pacastillo @frchavez @mjdiazster

**Comment by ccottap** [comment]
Shall we add OS information for each device?

**Comment by fcofdezdevega** [comment]
It would be of interest to add OS.

Paco.

**Comment by ccottap** [comment]
Added for Mac. Please everyone include this info in the table.

**Comment by fcofdezdevega** [comment]
Añadido.  Falta solamente la versión del SSOO en algunos casos.
