### ISSUE TITLE
Homogeneize section on methodology

### ISSUE THREAD

**Issue by ccottap** [frchavez/PPSN_Consumo_2016#9]
I have added some internal structure to this section, firstly discussing the algorithmic setting in one subsection and then going to describe the hardware in another (the order can be reversed if anyone feels it is better the other way around).

Regarding HW, I added some unnumbered subsubsections for each platform, in order to detail the data collection procedure. I have completed the part on the iMac. Please, check this and see if you can homogeneize the description for each system along similar lines. Whenever software is used, I think it would be good to use a footnote with a link (maybe better than a citation, also for space reasons). cc: @pacastillo @frchavez @mjdiazster 

@fcofdezdevega There is some text on FPGA that could be removed, couldn't it?

**Comment by ccottap** [comment]
The data collection procedure must be clearly detailed for each system. Please, detail:

- which quantities are being monitored.
- which app is used for that (with an appropriate link better than a ref) if any.
- how measurements are done (sampling at a certain frequency or gathering data at the end of runs, etc.)
- whether measurements are net or gross (and in this case how the base state is obtained in order to compute net values).
- any other relevant part of the experimentation that might exist.

**Comment by pacastillo** [comment]
Done for the Android case.

**Comment by mjdiazster** [comment]
Done for the laptop and raspberry pi. However, I'll appreciate someone has a look, just in case my English is not correct or you consider I have to add or modify something else.
Thanks.
